name: "oci-mirror"
version: "0.1.0"
usage: "Please see https://github.com/bloodorangeio/helm-oci-mirror for usage"
description: "mirror a helm repo in an OCI repository"
command: "$HELM_PLUGIN_DIR/bin/oci-mirror"
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
