name: build-pr

on:
  pull_request:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-pip python3-setuptools && sudo pip3 install virtualenv
      - name: checkout source code
        uses: actions/checkout@master
      - name: setup go environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.14.3'
      - name: run tests
        run: make clean acceptance
      - name: upload test report
        uses: actions/upload-artifact@master
        with:
          name: helm-oci-mirror-report-${{ github.sha }}
          path: .robot/
        if: always()
